RC0.1
zpd-digital-editions/narragonia-latina-oxygen pull request #37
Opened 2024-03-05 16:53 UTC by jroth16

2024-03-13 14:28 UTC, Kolophonium0 requested changes

2024-03-13 14:28 UTC, Kolophonium0 commented on ediarum.earlyprint.edit.framework
> +																		<String>&lt;g rend="initial" xmlns="http://www.tei-c.org/ns/1.0" style="font-size=${ask('Schriftgröße der Initiale', radio, ('big':'Big';'medium':'Medium';'small':'Small'),'big')}"/
font-size: large;
font-size: x-large;
font-size: xx-large;
Es geht ja um Initialen, die immer? grösser sind als der normale text.

2024-03-13 14:28 UTC, Kolophonium0 commented on resources/css/main.css
> +@import url("../../../ediarum.BASE.edit/css/standard.css");
gif. kannst du mal schauen, ob wir das robuster mit oxygen variablen hinbekommen $framework oder so

2024-03-27 12:43 UTC, jroth16 commented on ediarum.earlyprint.edit.framework
> +																		<String>&lt;g rend="initial" xmlns="http://www.tei-c.org/ns/1.0" style="font-size=${ask('Schriftgröße der Initiale', radio, ('big':'Big';'medium':'Medium';'small':'Small'),'big')}"/
Ich habe die Werte dementsprechend im css angepasst

2024-03-27 12:43 UTC, jroth16 commented on resources/css/main.css
> +@import url("../../../ediarum.BASE.edit/css/standard.css");
ich habe leider keinen Weg gefunden, dies mit einer oxygen variable zu lösen

2024-03-28 11:15 UTC, Kolophonium0 requested changes

2024-03-28 11:15 UTC, Kolophonium0 commented on ediarum.earlyprint.edit.framework
Genau das meinte ich 👎 Nicht im css Ändern, sondern im ask selbst:
`style="font-size: ${ask('Schriftgröße der Initiale', radio, ('xx-large':'Big';'x-large':'Medium';'large':'Small'),'big')}"` ist ja dann schon valides css.

2024-04-25 10:17 UTC, merged